# Buildspec for compiling angular project
version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 12
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - echo Installing Angular CLI...
        - npm install -g @angular/cli
  build:
    commands:
        - echo Build started 
        - ng build --prod
        - echo Build completed 
artifacts:
  files:
    - '**/*'
  base-directory: dist/test-app